# Generated by Django 3.2.5 on 2021-07-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type_transaction',
            field=models.CharField(choices=[('BUY', 'Buy stocks'), ('SELL', 'Sell stocks')], max_length=5, null=True),
        ),
    ]
