# Generated by Django 3.2.5 on 2021-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_item', to='trading.item'),
        ),
    ]
