# Generated by Django 3.2 on 2021-08-11 06:40

from django.db import migrations

from trading import apps


def update_price(apps, schema_editor):
    Offer = apps.get_model('trading', 'Offer')

    for offer in Offer.objects.all():
        offer.price += 500
        offer.save(update_fields=['price'])


class Migration(migrations.Migration):
    dependencies = [
        ('trading', '0009_auto_20210719_1046'),
    ]

    operations = [
        migrations.RunPython(update_price),
    ]
