# Generated by Django 3.2.5 on 2021-08-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_auto_20210830_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='counts_views',
        ),
    ]
