# Generated by Django 3.2 on 2021-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_remove_offer_counts_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
