# Generated by Django 3.2 on 2021-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_trade_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Requested price'),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
