# Generated by Django 3.2 on 2021-09-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_userprofile_stripe_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buyer_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_trade', to='trading.offer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_trade', to='trading.offer'),
        ),
    ]
