# Generated by Django 3.2.5 on 2021-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='workshifts',
            field=models.ManyToManyField(blank=True, related_name='assigned_positions', to='work_shift.WorkShift'),
        ),
    ]
